format = """$container\
$shell\
$python\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

add_newline = false

[container]
style = "cyan dimmed"
symbol = "\uf4b7"

[shell]
disabled = false
format = '[$indicator]($style)'
zsh_indicator = ''
nu_indicator = 'nu '
style = 'red'

[python]
pyenv_version_name = true
pyenv_prefix = ''
style = 'green bold'
format = '[py${pyenv_prefix}(${version} ) (\[$virtualenv\] )]($style)'

[directory]
style = "blue"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❯](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
